# Self-Release: For workflow-only repositories
# Use this pattern to release repos containing only reusable workflows
name: CI/CD

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    uses: jacaudi/github-actions/.github/workflows/lint.yml@main
    with:
      yaml: true

  version:
    needs: [lint]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: jacaudi/github-actions/.github/workflows/semantic-release.yml@main
    with:
      use-github-app: true
    secrets:
      app-id: ${{ secrets.APP_ID }}
      app-private-key: ${{ secrets.APP_PRIVATE_KEY }}

  release:
    needs: [lint, version]
    if: needs.version.outputs.new-release-published == 'true'
    uses: jacaudi/github-actions/.github/workflows/release.yml@main
    with:
      release-tag: ${{ needs.version.outputs.new-release-version }}
      create-release: true
      build-type: none
    secrets: inherit
